name: 'Sync fork with parent repository'

on:
  schedule:
    - cron: '*/3 * * * *' # every 3 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
#         token: ${{ secrets.PERSONAL_TOKEN }}
          owner: galek
          repo: 'minio/minio'
          base: master
          head: master
          merge_method: merge
          pr_title: 'Fork Sync with main repository'
          pr_message: 'Fork Sync with main repository'
#         ignore_fail: ''